# Generated by Django 4.2.5 on 2023-09-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
