# Generated by Django 4.2.5 on 2023-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.IntegerField()),
                ('FirstName', models.CharField(verbose_name=50)),
                ('LastName', models.CharField(verbose_name=50)),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
