# Generated by Django 4.2.5 on 2023-09-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='FirstName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='LastName',
            field=models.CharField(),
        ),
    ]
